# Generated by Django 3.2 on 2022-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_auto_20220131_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='amount',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
